Practice one
thanhnguyen-agilityio/tien-vo-thanh-internship pull request #139
Opened 2023-08-07 03:45 UTC by TIEN1909

#134 practice-one exercise-one

2023-08-07 04:00 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/about-me/aboutme.html
> +<!DOCTYPE html>
Please help update naming file `aboutme` -> `about-me`

2023-08-07 04:00 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/about-me/aboutme.html
> +    <div class="imageContainer"></div>
`imageContainer` -> `image-container`. Please help to recheck for all

2023-08-07 04:01 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/about-me/aboutme.js
> +//Add a style tag that sets a rule for "listitem" to make the color red.
Add space after `//` Please recheck for the rest

2023-08-07 04:03 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/about-me/aboutme.js
> +  listItem.style.color = "red";
This is not the right one.  Please use class to styling

2023-08-07 04:04 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/about-me/aboutme.js
> +if (img) {
Is any chance that img has falsy value?

2023-08-07 04:05 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/about-me/aboutme.js
> +if (img) {
Add breakline before and after each `if`. Please recheck for all

2023-08-07 04:06 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/the-book-list/app.js
> +    alreadyRead: false,
I recommend for props, variables that is boolean should have the prefix `is`, `has`. For example: `isRead`, `hasSomething`

2023-08-07 04:10 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/the-book-list/app.js
> +books.forEach((book) => {
Can we destruct `book` here?

2023-08-07 04:10 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/the-book-list/app.js
> +    bookItem.style.color = "red";
Please use `class` for styling instead

2023-08-07 04:13 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/the-book-list/app.js
> +  const bookDescription = document.createTextNode(book.title + " by " + book.author);
https://eslint.org/docs/latest/rules/prefer-template

2023-08-07 04:14 UTC, hungdo-agilityio commented on javascript-training/practice-one/exercise-one/the-logo-hijack/app.js
> +const logoGoogle = document.querySelector("img.lnXdpd");
Please help to add comments to this file. I dont' know where this script used

2023-08-08 06:43 UTC, tungtran-agilityio commented on javascript-training/practice-one/exercise-one/the-logo-hijack/app.js
> +const btnSearch = document.querySelector("input.gNO89b");
?

2023-08-08 06:47 UTC, tungtran-agilityio commented on javascript-training/package.json
> +{
I think you use create npm project for each exercise

2023-08-08 06:48 UTC, tungtran-agilityio requested changes
Please init npm project for each exercise

2023-08-08 07:50 UTC, tungtran-agilityio approved these changes

2023-08-08 08:02 UTC, closed without merging