Feat/Javascript-practice
thanhnguyen-agilityio/tien-vo-thanh-internship pull request #153
Opened 2023-08-25 11:11 UTC by TIEN1909

Init folder structure and create file README.md

2023-08-28 06:36 UTC, hungdo-agilityio commented on pomodoro-app/json-server/package.json
> +    "json-server": "^0.17.3"
Simply install json-server with the outer project or create another one separate from this project. No need to nest like this

2023-08-28 06:37 UTC, hungdo-agilityio commented on pomodoro-app/.eslintrc.js
> +module.exports = {
Please help to research config prettier rules in eslint

2023-08-28 06:37 UTC, hungdo-agilityio commented on pomodoro-app/package.json
> +  }
Please research about dependencies and devDependencies then clarify this

2023-08-28 06:39 UTC, hungdo-agilityio commented on pomodoro-app/src/index.html
> +<!DOCTYPE html>
From your design, it has multiple pages (home, login) do you have a folder for these html??

2023-08-28 06:40 UTC, hungdo-agilityio commented on pomodoro-app/.eslintrc.js
> +module.exports = {
And also help to install Airbnb rules for javascript

2023-08-28 06:45 UTC, TIEN1909 commented on pomodoro-app/src/index.html
> +<!DOCTYPE html>
yes, I will create an extra home.html file when I login to the project

2023-08-29 02:29 UTC, hungdo-agilityio commented on pomodoro-app/.eslintrc.js
> +    },
Did you check these configs?

2023-08-29 02:29 UTC, hungdo-agilityio commented on pomodoro-app/.eslintrc.js
> +    },
And where is airbnb config

2023-08-29 02:32 UTC, hungdo-agilityio commented on pomodoro-app/.eslintrc.js
> +        },
You have `.test.*` extension files?

2023-08-29 02:32 UTC, hungdo-agilityio commented on pomodoro-app/.eslintrc.js
> +        },
Why we override these rules? What are the default rules?

2023-08-29 02:33 UTC, hungdo-agilityio commented on pomodoro-app/README.md
> +- pnpm which usually comes with Node.js.
Which version?

2023-08-29 02:33 UTC, hungdo-agilityio commented on pomodoro-app/package.json
> +    "eslint-plugin-prettier": "^5.0.0",
You install these, but you use these?

2023-08-29 02:33 UTC, hungdo-agilityio commented on pomodoro-app/src/index.html
> +  <title>Pomodoro-app</title>
Pomodoro only

2023-08-29 02:34 UTC, hungdo-agilityio commented on pomodoro-app/src/styles/base/typography.css
> +@font-face {
Why code skeleton has this?

2023-08-29 02:35 UTC, hungdo-agilityio commented on pomodoro-app/src/styles/base/reset.css
> +/* http://meyerweb.com/eric/tools/css/reset/
same as below

2023-08-29 07:39 UTC, hungdo-agilityio commented on pomodoro-app/.eslintrc.json
> +    "jasmine": true
Can you explain `jasmine: true` to me

2023-08-29 07:41 UTC, thanhnguyen-agilityio commented on json-server/.gitignore
> +node_modules
Why need .gitignore in `json-server` folder?

2023-08-29 07:42 UTC, thanhnguyen-agilityio commented on pomodoro-app/.gitignore
> +node_modules
Why need .gitignore in `pomodoro-app` folder?

2023-08-29 07:46 UTC, TIEN1909 commented on pomodoro-app/.gitignore
> +node_modules
because when I run the server it creates a node_modules folder so I figured out how to create a .gitgnore file to prevent this

2023-08-29 07:46 UTC, TIEN1909 commented on json-server/.gitignore
> +node_modules
because when I run the server it creates a node_modules folder so I figured out how to create a .gitgnore file to prevent this

2023-08-29 07:55 UTC, thanhnguyen-agilityio commented on pomodoro-app/src/assets/fonts/.gitkeep
Dont need this file anymore since this folder is not empty.

2023-08-29 07:56 UTC, thanhnguyen-agilityio commented on pomodoro-app/src/scripts/services/.gitkeep
Why you need a service folder? Is this belong to MVC or any reason?

2023-08-29 07:56 UTC, closed without merging

2023-08-29 07:56 UTC, thanhnguyen-agilityio commented on pomodoro-app/src/styles/base/.gitkeep
Don't need this one anymore.

2023-08-29 07:57 UTC, thanhnguyen-agilityio requested changes

2023-08-29 07:57 UTC, thanhnguyen-agilityio commented on pomodoro-app/src/styles/vendors/.gitkeep
What is this folder for?

2023-08-29 07:57 UTC, thanhnguyen-agilityio commented on pomodoro-app/src/styles/components/.gitkeep
Don't need this one anymore.

2023-08-29 07:58 UTC, thanhnguyen-agilityio commented on json-server/.gitignore
> +node_modules
Where is your `.git` folder?

2023-08-29 08:04 UTC, TIEN1909 commented on json-server/.gitignore
> +node_modules
I see it shows a lot of change files so I do the same. I will update it